apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-persistent-claim-<your-name>
  namespace: <your-name>
spec:
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi