kind: PersistentVolume
apiVersion: v1
metadata:
  name: log-persistent-volume
  labels:
    type: local
spec:
  volumeMode: Filesystem
  storageClassName: demo
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-persistent-claim
spec:
  volumeMode: Filesystem
  storageClassName: demo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
