apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume-aditya
  namespace: aditya
  labels:
    type: local
spec:
  storageClassName: aditya-mysql
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data-aditya"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim-aditya
  namespace: aditya
spec:
  storageClassName: aditya-mysql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi