apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume-ashish
  namespace: ashish
  labels:
    type: local
spec:
  storageClassName: mysql-ashish
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data-ashish"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim-ashish
  namespace: ashish
spec:
  storageClassName: mysql-ashish
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi