apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pages
    servicefor: pages
  name: pages
  namespace: ashish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pages
      servicefor: pages
  strategy: {}
  template:
    metadata:
      labels:
        app: pages
        servicefor: pages
    spec:
      volumes:
      - name: log-volume
        emptyDir: {}
      containers:
        - image: senappaa/pages:persist
          imagePullPolicy: Always
          env:
            - name: PAGE_CONTENT
              valueFrom:
                configMapKeyRef:
                  name: pages-config-map
                  key: PAGE_CONTENT
          name: pages
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: log-volume
            mountPath: "/var/tmp/"
          readinessProbe:
              tcpSocket:
                port: 8080
              initialDelaySeconds: 150
              periodSeconds: 5
              successThreshold: 2
          livenessProbe:
              httpGet:
                path: /actuator/health
                port: 8080
              initialDelaySeconds: 150
              periodSeconds: 5
              successThreshold: 1
          resources: {}
status: {}