apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pages
    servicefor: pages
  name: pages
  namespace: ashish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pages
      servicefor: pages
  strategy: {}
  template:
    metadata:
      labels:
        app: pages
        servicefor: pages
    spec:
      containers:
      - image: senappaa/pages:1.0
        imagePullPolicy: Always
        name: pages
        ports:
          - containerPort: 8080
        resources: {}
        - image: senappaa/pages:config
          imagePullPolicy: Always
          env:
          - name: PAGE_CONTENT
            valueFrom:
               configMapKeyRef:
                 name: pages-config-map
                 key: PAGE_CONTENT
          name: pages
          ports:
            - containerPort: 8080
          resources: {}
>>>>>>> config-work
status: {}