apiVersion: v1
kind: Service
metadata:
  labels:
    app:
    servicefor:
  name:
  namespace:
spec:
  ports:
  - port:
    protocol:
    targetPort:
  selector:
    app:
    servicefor:
  type: LoadBalancer
status:
  loadBalancer: {}
